### ISSUE TITLE
Update README to Swift 3

### ISSUE THREAD

**Issue by lfarah** [Albin-CR/SwiftyTask#1]
Hey @Albin-CR, please update your example code to Swift 3, using ```Date()``` instead of ```NSDate()```

**Comment by lfarah** [comment]
Please fix this [before I can merge your PR](https://github.com/vsouza/awesome-ios/pull/1445#issuecomment-277588372)

**Comment by Albin-CR** [comment]
@ifarah I created a new pull request [Link ](https://github.com/vsouza/awesome-ios/pull/1462)
